### ISSUE TITLE
Error while building using Docker

### ISSUE THREAD

**Issue by hosseinabdinf** [TrustworthyComputing/T2-FHE-Compiler-and-Benchmarks#20]
Hi,

I got following error while trying to build repo using Docker:
  
  ```
=> ERROR [11/13] RUN .circleci/clone_libs.sh                                                                      0.3s
  ------
   > [11/13] RUN .circleci/clone_libs.sh:
  0.246 + .circleci/clone_libs.sh
  0.246 /bin/bash: .circleci/clone_libs.sh: /bin/bash^M: bad interpreter: No such file or directory
  ------
  Dockerfile:23
  --------------------
    21 |
    22 |     # Clone HE libraries
    23 | >>> RUN .circleci/clone_libs.sh
    24 |
    25 |     # Build HE libraries
  --------------------
  ERROR: failed to solve: process "/bin/bash -exo pipefail -c .circleci/clone_libs.sh" did not complete successfully: exit code: 126
```

Here is my current configuration:

> Docker version: 4.26.1
> WSL version: 2.0.9.0
> Kernel version: 5.15.133.1-1
> WSLg version: 1.0.59
> MSRDC version: 1.2.4677
> Direct3D version: 1.611.1-81528511
> DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
> Windows version: 10.0.22621.2861

Thanks

**Comment by jimouris** [comment]
Hey, on what platform are you building it? We've mostly tested on Linux-based distributions.

**Comment by cgouert** [comment]
The issue lies in the line ending formats between Unix and Windows. I was able to successfully build the docker on Windows by downloading [dos2unix](https://dos2unix.sourceforge.io/) and then running `dos2unix.exe .\.circleci\build_libs.sh` and `dos2unix.exe .\.circleci\clone_libs.sh` before running the Docker build step.

**Comment by hosseinabdinf** [comment]
@cgouert dos2unix worked. Thanks!
